### ISSUE TITLE
Search request feature does not scale with large ontologies

### ISSUE THREAD

**Issue by SimonCommits** [lca1/medco-connector#122]
Hello,

I made some tests on the new search feature locally on my computer this morning. The amount of requests that are sent to the back-end in order fetch information about the matching concepts is quite enormous. In my ontology I have 606 240 medical concepts. 

I tried to type "test" in the glowing bear search bar. It resulted in a thousand HTTP queries which took 1 min and 40 seconds to be returned. Sending that many requests made my browser freeze. I think the source of that many requests is the fact that for each concept returned by the search query a _concept info_ request is sent. It would be nice to group all those info requests into one single HTTP request. 

I know this would take some work. But I think it would help make the software more scalable and usable.

**Comment by jimmydjabali** [comment]
@f-marino We may need to look at this

**Comment by SimonCommits** [comment]
@f-marino @Fasjul @jimmydjabali 
It seems that for each character added to the search input a new request is executed. Maybe we should wait for the user to be done typing the entire search phrase before launching a query to the backend? A button could be added to the search panel. And only if this button is clicked the query would be executed.

**Comment by Fasjul** [comment]
1. When searching for "test", it looks like search queries for substrings in "test" (including "tes" for example)
2. The backend response does not include the display name of the n matching ontology elements, so that makes n additional calls to get those display names, not mentioning the ancestors queries (might be solved at the same time)
3. The detailed paths does not seem to always include the last element, which looks like an error (the bold element should be present every time)
4. A lot of errors with code 500 appear when we try it. were you able to test the feature with the test SPHN ontology (that is currently in the medco-demo.epfl.ch deployment)?

**Comment by SimonCommits** [comment]
Adding such indexes on the different nodes database and https://github.com/ldsec/medco/pull/123 fix the problem.

CREATE INDEX META_FULLNAME_IDX ON medco_ont.sphn(C_FULLNAME);
CREATE INDEX META_APPLIED_PATH_IDX ON medco_ont.sphn(M_APPLIED_PATH);
CREATE INDEX META_EXCLUSION_IDX ON medco_ont.sphn(M_EXCLUSION_CD);
CREATE INDEX META_HLEVEL_IDX ON medco_ont.sphn(C_HLEVEL);
CREATE INDEX META_SYNONYM_IDX ON medco_ont.sphn(C_SYNONYM_CD);
CREATE INDEX META_CNAME_IDX ON medco_ont.sphn(C_NAME);
